title       = "mangafire"
baseURL     = "https://mangafire-cli.tamnd.com/"
description = "A command line for mangafire."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/mangafire-cli"
